/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sadili_vincent_inf222_finals;

import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;

/**
 *
 * @author vincent
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
      
       
    }
        public class taymer implements ActionListener{
        public void actionPerformed(ActionEvent evt){
            int lod = jProgressBar1.getValue();
            if(lod<100){
                lod+=10;
                jLabel1.setText("Loading "+lod+"%");
                jProgressBar1.setValue(lod);
            }else{
                tm.stop();
               JOptionPane.showMessageDialog(null,"Log in Sucessful"); 
              CashierFrame n= new CashierFrame();
              n.setVisible(true);
              LoginFrame.this.setVisible(false);
              
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);
        jPanel2.add(jPasswordField2);
        jPasswordField2.setBounds(200, 170, 180, 23);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(200, 120, 180, 23);

        jButton4.setText("Login");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(100, 280, 72, 23);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Username:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(130, 120, 70, 17);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(130, 170, 70, 17);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(592, 330, 100, 23);
        jPanel2.add(jProgressBar1);
        jProgressBar1.setBounds(0, 360, 700, 10);

        jToggleButton1.setText("Show Password");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton1);
        jToggleButton1.setBounds(200, 210, 180, 23);

        jLabel1.setText("Loading");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 330, 100, 17);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sadili_vincent_inf222_finals/Kahit.png"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 700, 400);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 700, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
                if(jToggleButton1.isSelected()){
            jToggleButton1.setText("Hide Password");
            jPasswordField2.setEchoChar((char)0);
            
        }else{
            jPasswordField2.setEchoChar('*');
            jToggleButton1.setText("show Password");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed
     public static String job="";
     public static String name="";
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MMM-dd");
        Date time = new Date();
        SimpleDateFormat sdt = new SimpleDateFormat("hh:mm:a");
        
        
        String uname1 = jTextField2.getText();
        String pass1 = jPasswordField2.getText();
        int a = UserAccount.username.size();
        
        int i;
        if(jTextField2.getText().equals(SuperAdmin.username) && 
           jPasswordField2.getText().equals(SuperAdmin.password)){
            job="Super Admin";
            name="Vincent";
            UserAccount.AccountLog.add(name);
            UserAccount.Date.add(sdf.format(date));
            UserAccount.TimeIn.add(sdt.format(time));
            UserAccount.Timeout.add("Still Active");
            tm=new Timer(100,new LoginFrame.taymer());
            tm.start();
        }else if(UserAccount.username.indexOf(uname1)>=0){
            for (i = 0; i < a; ) 
            {
                if (!uname1.equals(UserAccount.username.get(i))) 
                {
                    i++;
                }
                else{
                    if (!pass1.equals(UserAccount.password.get(i))) 
                    {
                        JOptionPane.showMessageDialog(null, "Incorrect Password for " + uname1 + " account.");
                        jTextField2.setText("");
                        break;
                    }
                    else
                    {
                      if(UserAccount.accountStat.get(i).equalsIgnoreCase("ACTIVATED")){
                          if(UserAccount.job.get(i).equalsIgnoreCase("Cashier")){
                              job="Cashier";
                          }else if(UserAccount.job.get(i).equalsIgnoreCase("Admin")){
                              job="Admin";
                          }else if(UserAccount.job.get(i).equalsIgnoreCase("Super Admin")){
                              job="Super Admin";
                          }
                          name=UserAccount.Fullname.get(i);
                          UserAccount.AccountLog.add(name);
                          UserAccount.Date.add(sdf.format(date));
                          UserAccount.TimeIn.add(sdt.format(time));
                          UserAccount.Timeout.add("Still Active");
                          
                         
                         
                       tm=new Timer(100,new LoginFrame.taymer());
                       tm.start();
                       break; 
                      }else{
                        JOptionPane.showMessageDialog(null, "Account is DEACTIVATED");  
                        break; 
                      }
                       
                    }
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Account doesn't exist!");
            jTextField2.setText("");
            jPasswordField2.setText("");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }
    
 
public static Timer t ;

private Timer tm;

   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
