/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sadili_vincent_inf222_finals;

import javax.swing.JOptionPane;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
/**
 *
 * @author vincent
 */
public class PaymentFrame extends javax.swing.JFrame {

    /**
     * Creates new form PaymentFrame
     */
    public PaymentFrame() {
        initComponents();
        getReceiptButton.setEnabled(false);
        receiveButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CosNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pModejComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Button100 = new javax.swing.JButton();
        Button200 = new javax.swing.JButton();
        Button500 = new javax.swing.JButton();
        Button1000 = new javax.swing.JButton();
        Changetxt = new javax.swing.JLabel();
        receiveButton = new javax.swing.JButton();
        payButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        getReceiptButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cusTypeComboBox = new javax.swing.JComboBox<>();
        Discounttxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 6, true));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Name");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Type:");

        pModejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Bank", "Gcash" }));
        pModejComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pModejComboBoxItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Payment Mode:");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount:");

        Button100.setText("100");
        Button100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button100ActionPerformed(evt);
            }
        });

        Button200.setText("200");
        Button200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button200ActionPerformed(evt);
            }
        });

        Button500.setText("500");
        Button500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button500ActionPerformed(evt);
            }
        });

        Button1000.setText("1000");
        Button1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1000ActionPerformed(evt);
            }
        });

        Changetxt.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Changetxt.setForeground(new java.awt.Color(255, 255, 255));
        Changetxt.setText("Change: ");

        receiveButton.setText("Receive");
        receiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveButtonActionPerformed(evt);
            }
        });

        payButton.setText("PAY");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TOTAL: "+CashierFrame.getSum());

        getReceiptButton.setText("Get Receipt");
        getReceiptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getReceiptButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cusTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Senior Citizen", "PWD" }));
        cusTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cusTypeComboBoxItemStateChanged(evt);
            }
        });

        Discounttxt.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Discounttxt.setForeground(new java.awt.Color(255, 255, 255));
        Discounttxt.setText("Discount:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(payButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(CosNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(receiveButton)))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Changetxt)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Button100)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button200)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button500)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button1000))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pModejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cusTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Discounttxt))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(getReceiptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CosNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cusTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pModejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiveButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(amountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button100)
                    .addComponent(Button200)
                    .addComponent(Button500)
                    .addComponent(Button1000))
                .addGap(18, 18, 18)
                .addComponent(Changetxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Discounttxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getReceiptButton)
                    .addComponent(jButton1))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pModejComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pModejComboBoxItemStateChanged
        // TODO add your handling code here:
         String mode=pModejComboBox.getSelectedItem().toString();
        if(mode.equalsIgnoreCase("cash")){
            this.setTrans("Cash");
            receiveButton.setEnabled(false);
            amountTextField.setEditable(true);
            amountTextField.setEnabled(true);
            payButton.setEnabled(true);
        }else{
            if(mode.equalsIgnoreCase("Gcash")){
             this.setTrans("Gcash");   
            }else if(mode.equalsIgnoreCase("Bank")){
              this.setTrans("Bank");   
            }
            receiveButton.setEnabled(true);
            amountTextField.setEditable(false);
            amountTextField.setEnabled(false);
            payButton.setEnabled(false);
        }
    }//GEN-LAST:event_pModejComboBoxItemStateChanged

    private void Button100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button100ActionPerformed
        // TODO add your handling code here:
        amountTextField.setText("100");
    }//GEN-LAST:event_Button100ActionPerformed

    private void Button200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button200ActionPerformed
        // TODO add your handling code here:
        amountTextField.setText("200");
    }//GEN-LAST:event_Button200ActionPerformed

    private void Button500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button500ActionPerformed
        // TODO add your handling code here:
        amountTextField.setText("500");
    }//GEN-LAST:event_Button500ActionPerformed

    private void Button1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1000ActionPerformed
        // TODO add your handling code here:
        amountTextField.setText("1000");
    }//GEN-LAST:event_Button1000ActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // TODO add your handling code here:
        String sAmount=amountTextField.getText();
        String total=CashierFrame.getSum();
        String payed=amountTextField.getText();
        this.setAmount(sAmount);
        double change=0;
        double t= Double.parseDouble(total);
        double a= Double.parseDouble(sAmount);
        if(a>t){
            change=a-t;
            getReceiptButton.setEnabled(true);
        }else if(a<t){
            JOptionPane.showMessageDialog(null, "inefficient balance");
        }
        String n = Double.toString(change);
        this.setChange(n);
        Changetxt.setText("Change: "+this.getChange());
    }//GEN-LAST:event_payButtonActionPerformed

    private void getReceiptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getReceiptButtonActionPerformed
        // TODO add your handling code here:
        String mode=pModejComboBox.getSelectedItem().toString();
        if(mode.equalsIgnoreCase("cash")){
            this.setTrans("Cash");
        }else{
            if(mode.equalsIgnoreCase("Gcash")){
             this.setTrans("Gcash");   
            }else if(mode.equalsIgnoreCase("Bank")){
              this.setTrans("Bank");   
            }
        
        }
        this.setCosName(CosNameTextField.getText());
        PaymentFrame.this.setVisible(false);
        ReceiptFrame n = new ReceiptFrame();
        n.setVisible(true);
    }//GEN-LAST:event_getReceiptButtonActionPerformed

    private void receiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveButtonActionPerformed
        // TODO add your handling code here:
        this.setAmount(CashierFrame.getSum());
        getReceiptButton.setEnabled(true);
         JOptionPane.showMessageDialog(null, "PAYMENT RECEIVE!");
    }//GEN-LAST:event_receiveButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PaymentFrame.this.setVisible(false);
        CashierFrame n = new CashierFrame();
        n.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cusTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cusTypeComboBoxItemStateChanged
        // TODO add your handling code here:
                String cusType=cusTypeComboBox.getSelectedItem().toString();
        double sum =Double.parseDouble(CashierFrame.getSum());
        double ogsum=Double.parseDouble(CashierFrame.getOgsum());
        double discount=0;
        if(cusType.equalsIgnoreCase("regular")){
             CashierFrame.setCtype("REGULAR");
           sum=ogsum;
        }else{
            if(cusType.equalsIgnoreCase("SENIOR CITIZEN")){
                 CashierFrame.setCtype("SENIOR CITIZEN");
            }else if(cusType.equalsIgnoreCase("PWD")){
                  CashierFrame.setCtype("PWD");
            }
            sum=ogsum;
            discount=sum*.20;
            sum=sum-discount;
        }
         CashierFrame.setDiscount(Double. toString(discount));
         CashierFrame.setSum(Double. toString(sum));
         Discounttxt.setText("Discount: "+CashierFrame.getDiscount());
         jLabel6.setText("TOTAL: "+CashierFrame.getSum());
    }//GEN-LAST:event_cusTypeComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentFrame().setVisible(true);
            }
        });
    }
    
    
    //--------------------------------------------------------------------------------------------------------------------------------
    
    private static final int MAX_NUMBER = 99999;  // Maximum value for each number segment
    private static final int SEGMENT_COUNT = 3;   // Number of segments in the output
    
    public static String generateUniqueNumber() {
        StringBuilder sb = new StringBuilder();
        
        for (int i = 0; i < SEGMENT_COUNT; i++) {
            int segment = generateUniqueSegment();
            sb.append(String.format("%05d", segment));  // Pad the segment with leading zeros
            if (i < SEGMENT_COUNT - 1) {
                sb.append("-");
            }
        }
        
        return sb.toString();
    }
    
    private static int generateUniqueSegment() {
        Set<Integer> generatedNumbers = new HashSet<>();
        Random random = new Random();
        
        while (true) {
            int segment = random.nextInt(MAX_NUMBER + 1);
            if (!generatedNumbers.contains(segment)) {
                generatedNumbers.add(segment);
                return segment;
            }
        }
    }
public static String amount="0";
public static String Change="0";
public static String CosName="";
public static String Trans="";
public static String TranNo="";
public static String RefNo="";

    public static String getTranNo() {
        return TranNo;
    }

    public static void setTranNo(String TranNo) {
        PaymentFrame.TranNo = TranNo;
    }

    public static String getRefNo() {
        return RefNo;
    }

    public static void setRefNo(String RefNo) {
        PaymentFrame.RefNo = RefNo;
    }

    public static String getTrans() {
        return Trans;
    }

    public static void setTrans(String Trans) {
        PaymentFrame.Trans = Trans;
    }

    public static String getCosName() {
        return CosName;
    }

    public static void setCosName(String CosName) {
        PaymentFrame.CosName = CosName;
    }

    public static String getAmount() {
        return amount;
    }

    public static void setAmount(String amount) {
        PaymentFrame.amount = amount;
    }

    public static String getChange() {
        return Change;
    }

    public static void setChange(String Change) {
        PaymentFrame.Change = Change;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button100;
    private javax.swing.JButton Button1000;
    private javax.swing.JButton Button200;
    private javax.swing.JButton Button500;
    private javax.swing.JLabel Changetxt;
    private javax.swing.JTextField CosNameTextField;
    private javax.swing.JLabel Discounttxt;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JComboBox<String> cusTypeComboBox;
    private javax.swing.JButton getReceiptButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> pModejComboBox;
    private javax.swing.JButton payButton;
    private javax.swing.JButton receiveButton;
    // End of variables declaration//GEN-END:variables
}
