/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sadili_vincent_inf222_finals;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vincent
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
    public RegisterFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        adminCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fullnameF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cashierCheckBox = new javax.swing.JCheckBox();
        superCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(200, 90, 220, 23);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(200, 120, 220, 23);
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(200, 150, 220, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(160, 180, 80, 23);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(240, 180, 72, 23);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(310, 180, 72, 23);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Male");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(160, 230, 51, 21);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Female");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(240, 230, 65, 21);

        buttonGroup2.add(adminCheckBox);
        adminCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        adminCheckBox.setText("Admin");
        adminCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(adminCheckBox);
        adminCheckBox.setBounds(340, 270, 60, 21);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 90, 80, 17);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 120, 80, 20);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Re-Type Password:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 150, 130, 20);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Birthday:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 180, 80, 20);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 230, 70, 20);
        jPanel1.add(fullnameF);
        fullnameF.setBounds(200, 60, 220, 23);

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Full Name:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 60, 110, 17);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(70, 270, 72, 23);

        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(160, 270, 140, 23);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 160, 60, 0);

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" |      MM        |       DD      |       YY      |");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(150, 200, 260, 20);

        buttonGroup2.add(cashierCheckBox);
        cashierCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cashierCheckBox.setSelected(true);
        cashierCheckBox.setText("Cashier");
        jPanel1.add(cashierCheckBox);
        cashierCheckBox.setBounds(340, 290, 67, 21);

        buttonGroup2.add(superCheckBox);
        superCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        superCheckBox.setText("Super Admin");
        superCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                superCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(superCheckBox);
        superCheckBox.setBounds(340, 250, 110, 21);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sadili_vincent_inf222_finals/register.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if( UserAccount.Fullname.contains(fullnameF.getText()) || 
            UserAccount.username.contains(jTextField1.getText())){
            
            JOptionPane.showMessageDialog(null, "Account Already Existing!");
            
        }else if(fullnameF.getText().isEmpty() || 
                 jTextField1.getText().isEmpty() ||
                 jPasswordField1.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Please make sure to fill in all required fields.");
        }
        
        else{
            
        if(jPasswordField1.getText().equals(jPasswordField2.getText())){
        
         UserAccount.Fullname.add(fullnameF.getText());
        this.setFullname(fullnameF.getText());
        
        //---------------------------------------------
        UserAccount.username.add(jTextField1.getText());
        this.setUsername(jTextField1.getText());
        
       if(jPasswordField1.getText().equals(jPasswordField2.getText())){
           UserAccount.password.add(jPasswordField1.getText());
           this.setPassword(jPasswordField1.getText());
            jLabel3.setText("");
       }else{
           jLabel3.setText("Password dont match.Try again");
           
       }
       //---------------------------------------------
       
        String mon=jComboBox1.getSelectedItem().toString();
        String day=jComboBox2.getSelectedItem().toString();
        String yr=jComboBox3.getSelectedItem().toString();
        UserAccount.birthday.add(mon+" / "+day+" / "+yr);
        int year = Integer.parseInt(yr);
        UserAccount.age.add(2023-year+" Years Old");
        this.setAge(2023-year+" Years Old");
        
        //---------------------------------------------
        
          if(jRadioButton1.isSelected()){
            UserAccount.gender.add(jRadioButton1.getText());
            this.setGender(jRadioButton1.getText());
        }else if(jRadioButton2.isSelected()){
            UserAccount.gender.add(jRadioButton2.getText()); 
            this.setGender(jRadioButton2.getText());   
        }
        //---------------------------------------------
        if(adminCheckBox.isSelected()){
            UserAccount.job.add(adminCheckBox.getText());
            this.setJob(adminCheckBox.getText());
        }else if(cashierCheckBox.isSelected()){
            UserAccount.job.add(cashierCheckBox.getText());
            this.setJob(cashierCheckBox.getText());
        }else if(superCheckBox.isSelected()){
            UserAccount.job.add(superCheckBox.getText());
            this.setJob(superCheckBox.getText());
        }
          UserAccount.accountStat.add("ACTIVATED");
        this.setActivate("ACTIVATED");
        
        //&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
        
         int ctr = UserAccount.username.size() + 1;
        String data1 = Integer.toString(ctr);
        String data2 = this.getFullname();
        String data3 = this.getUsername();
        String data4 = this.getPassword();
        String data5 = this.getGender();
        String data6 = this.getBirthday();
        String data7 = this.getAge();
        String data8 = this.getActivate();
        String data9 = this.getJob();
        Object[] row = { data1, data2, data3,data4,data5,data6,data7,data8,data9  };
        if(data9.equals(adminCheckBox.getText())){
        DefaultTableModel model = (DefaultTableModel) AdminFrame.AdminTable.getModel();
        model.addRow(row);      
        }else if(data9.equals(cashierCheckBox.getText())){
        DefaultTableModel model = (DefaultTableModel) AdminFrame.CashierTable.getModel();
        model.addRow(row);  
        }
        
            
        

        
       
        }else{
        JOptionPane.showMessageDialog(null, "Password dont match.Try again!");
        jLabel3.setText("Password dont match.Try again");
        
        }
    }
       /* UserAccount.Fullname.add(jTextField2.getText());
        this.setFullname(jTextField2.getText());
        
        //---------------------------------------------
        UserAccount.username.add(jTextField1.getText());
        this.setUsername(jTextField1.getText());
        
       if(jPasswordField1.getText().equals(jPasswordField2.getText())){
           UserAccount.password.add(jPasswordField1.getText());
           this.setPassword(jPasswordField1.getText());
            jLabel3.setText("");
       }else{
           jLabel3.setText("Password dont match.Try again");
       }
       //---------------------------------------------
       
        String mon=jComboBox1.getSelectedItem().toString();
        String day=jComboBox2.getSelectedItem().toString();
        String yr=jComboBox3.getSelectedItem().toString();
        UserAccount.birthday.add(mon+" "+day+", "+yr);
        int year = Integer.parseInt(yr);
        UserAccount.age.add(2023-year+" Years Old");
        this.setAge(2023-year+" Years Old");
        
        //---------------------------------------------
        
          if(jRadioButton1.isSelected()){
            UserAccount.gender.add(jRadioButton1.getText());
            this.setGender(jRadioButton1.getText());
        }else if(jRadioButton2.isSelected()){
            UserAccount.gender.add(jRadioButton2.getText()); 
            this.setGender(jRadioButton2.getText());   
        }
        //---------------------------------------------
        
          UserAccount.accountStat.add("ACTIVATED");
        this.setActivate("ACTIVATED");
        
        //&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
        
         int ctr = UserAccount.username.size() + 1;
        String data1 = Integer.toString(ctr);
        String data2 = this.getFullname();
        String data3 = this.getUsername();
        String data4 = this.getPassword();
        String data5 = this.getGender();
        String data6 = this.getBirthday();
        String data7 = this.getAge();
        String data8 = this.getActivate();
        Object[] row = { data1, data2, data3,data4,data5,data6,data7,data8  };
        DefaultTableModel model = (DefaultTableModel) AdminFrame.jTable1.getModel();
        model.addRow(row);*/
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jButton2.getText().equalsIgnoreCase("Back to Login")){
            LoginFrame n =new LoginFrame();
            n.setVisible(true);
        }else if (jButton2.getText().equalsIgnoreCase("Confirm")){
          AdminFrame n = new AdminFrame();
        n.setVisible(true);  
        }
        
        RegisterFrame.this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void superCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_superCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_superCheckBoxActionPerformed

    private void adminCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminCheckBoxActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

public static String Fullname;   
public static String username;
public static String password;
public static String birthday;
public static String gender;
public static String activate;
public static int year;
public static String Age;
public static String job;

    public static String getJob() {
        return job;
    }

    public static void setJob(String job) {
        RegisterFrame.job = job;
    }
    public static String getActivate() {
        return activate;
    }

    public static void setActivate(String activate) {
        RegisterFrame.activate = activate;
    }
    public static String getFullname() {
        return Fullname;
    }

    public static void setFullname(String Fullname) {
        RegisterFrame.Fullname = Fullname;
    }

    public static String getAge() {
        return Age;
    }

    public static void setAge(String Age) {
       RegisterFrame.Age = Age;
    }


    public static int getYear() {
        return year;
    }

    public static void setYear(int year) {
        RegisterFrame.year = year;
    }

    public static String getUsername() {
        return username;
    }

    public static void setUsername(String username) {
        RegisterFrame.username = username;
    }

    public static String getPassword() {
        return password;
    }

    public static void setPassword(String password) {
       RegisterFrame.password = password;
    }

    public static String getBirthday() {
        return birthday;
    }

    public static void setBirthday(String birthday) {
        RegisterFrame.birthday = birthday;
    }

    public static String getGender() {
        return gender;
    }

    public static void setGender(String gender) {
        RegisterFrame.gender = gender;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox adminCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public static javax.swing.JCheckBox cashierCheckBox;
    private javax.swing.JTextField fullnameF;
    private javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JCheckBox superCheckBox;
    // End of variables declaration//GEN-END:variables
}
